init:
  - ps: echo $env:TOXENV
  - ps: ls C:\Python*

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'
  matrix:
    - TOXENV: 'py27,lint'
      TOXPYTHON: C:\Python27\python.exe
      PYTHON_HOME: C:\Python27
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '32'

    - TOXENV: 'py27,lint'
      TOXPYTHON: C:\Python27-x64\python.exe
      WINDOWS_SDK_VERSION: v7.0
      PYTHON_HOME: C:\Python27-x64
      PYTHON_VERSION: '2.7'
      PYTHON_ARCH: '64'

    - TOXENV: 'py36,lint'
      TOXPYTHON: C:\Python36\python.exe
      PYTHON_HOME: C:\Python36
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '32'

    - TOXENV: 'py36,lint'
      TOXPYTHON: C:\Python36-x64\python.exe
      PYTHON_HOME: C:\Python36-x64
      PYTHON_VERSION: '3.6'
      PYTHON_ARCH: '64'


install:
  - 'git submodule update --init --recursive'
  - 'pip install tox'

build: off

test_script:
  - '%PYTHON_HOME%\\Scripts\\pip --version'
  - '%PYTHON_HOME%\\Scripts\\tox --version'
  - '%PYTHON_HOME%\\Scripts\\virtualenv --version'
  - '%WITH_COMPILER% %PYTHON_HOME%\\Scripts\\tox -e %TOXENV%'
